'use strict';
const {createCanvas,loadImage,GlobalFonts}=require('@napi-rs/canvas');
try{GlobalFonts.registerFromPath('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf','VY Sans');}catch{}
const FONT='VY Sans, Arial';
function round(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function fit(ctx,text,max){let out=String(text??'');while(out.length>1&&ctx.measureText(out).width>max)out=out.slice(0,-1);return out===String(text??'')?out:out+'…';}
async function avatar(ctx,url,x,y,size){ctx.save();ctx.beginPath();ctx.arc(x+size/2,y+size/2,size/2,0,Math.PI*2);ctx.clip();try{ctx.drawImage(await loadImage(url),x,y,size,size);}catch{ctx.fillStyle='#303552';ctx.fillRect(x,y,size,size);ctx.fillStyle='#fff';ctx.font=`700 ${Math.round(size*.38)}px ${FONT}`;ctx.textAlign='center';ctx.fillText('VY',x+size/2,y+size*.62);}ctx.restore();}
async function card({title,subtitle='',lines=[],accent='#5865F2',avatarUrl='',badge='VYBOT',footer='vybot • güvenli • görsel arayüz'}){const w=1100,h=Math.max(430,260+lines.length*62),c=createCanvas(w,h),x=c.getContext('2d'),g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,'#0a1020');g.addColorStop(.55,'#111a32');g.addColorStop(1,'#080c18');x.fillStyle=g;x.fillRect(0,0,w,h);x.fillStyle=accent;x.fillRect(0,0,14,h);x.globalAlpha=.16;const glow=x.createRadialGradient(900,50,0,900,50,430);glow.addColorStop(0,accent);glow.addColorStop(1,'transparent');x.fillStyle=glow;x.fillRect(0,0,w,h);x.globalAlpha=1;x.fillStyle='rgba(255,255,255,.06)';round(x,48,42,w-96,h-84,28);x.fill();x.strokeStyle='rgba(255,255,255,.12)';x.lineWidth=2;x.stroke();if(avatarUrl)await avatar(x,avatarUrl,78,75,112);const left=avatarUrl?220:82;x.textAlign='left';x.fillStyle=accent;x.font=`700 24px ${FONT}`;x.fillText(badge.toUpperCase(),left,96);x.fillStyle='#fff';x.font=`700 48px ${FONT}`;x.fillText(fit(x,title,790),left,151);x.fillStyle='#aeb8d3';x.font=`400 24px ${FONT}`;x.fillText(fit(x,subtitle,790),left,190);let y=245;for(const item of lines){const label=typeof item==='string'?'':item.label,value=typeof item==='string'?item:item.value;x.fillStyle='rgba(255,255,255,.055)';round(x,76,y-34,w-152,50,12);x.fill();x.fillStyle='#8793b5';x.font=`600 20px ${FONT}`;x.fillText(fit(x,label,300),94,y);x.fillStyle='#f5f7ff';x.font=`600 21px ${FONT}`;x.textAlign='right';x.fillText(fit(x,value,620),w-96,y);x.textAlign='left';y+=62;}x.fillStyle='#6f7b9c';x.font=`500 17px ${FONT}`;x.fillText(footer,80,h-58);return c.toBuffer('image/png');}
module.exports={card};
