'use strict';
const {SlashCommandBuilder,PermissionFlagsBits:P}=require('discord.js');
const U=t=>o=>o.setName('kullanici').setDescription(t).setRequired(true),R=t=>o=>o.setName('rol').setDescription(t).setRequired(true),reason=o=>o.setName('sebep').setDescription('İşlem sebebi').setMaxLength(300);
const commandData=[
...['yardim:Fotoğraflı interaktif komut rehberi','menu:Görsel ana menü','ping:Gecikme kartı','botbilgi:Canlı bot istatistikleri','sistem:Sistem kaynakları','davet:Bot davet paneli','sunucu:Sunucu bilgi kartı','liderlik:XP sıralaması','gunluk:Günlük coin ödülü','calis:Çalışarak coin kazan','zenginler:Ekonomi sıralaması','gec:Çalan parçayı geç','durdur:Müziği durdur','kuyruk:Görsel müzik kuyruğu'].map(x=>{const [n,d]=x.split(':');return new SlashCommandBuilder().setName(n).setDescription(d)}),
new SlashCommandBuilder().setName('profil').setDescription('Birleşik üye profil kartı').addUserOption(o=>o.setName('kullanici').setDescription('Üye')),
new SlashCommandBuilder().setName('rank').setDescription('Seviye ve XP kartı').addUserOption(o=>o.setName('kullanici').setDescription('Üye')),
new SlashCommandBuilder().setName('bakiye').setDescription('Ekonomi kartı').addUserOption(o=>o.setName('kullanici').setDescription('Üye')),
new SlashCommandBuilder().setName('kumar').setDescription('Görsel şans oyunu').addStringOption(o=>o.setName('oyun').setDescription('Oyun').setRequired(true).addChoices({name:'Slot',value:'slot'},{name:'Yazı tura',value:'coin'})).addIntegerOption(o=>o.setName('bahis').setDescription('Bahis').setMinValue(10).setRequired(true)).addStringOption(o=>o.setName('secim').setDescription('Seçim').addChoices({name:'Yazı',value:'yazi'},{name:'Tura',value:'tura'})),
new SlashCommandBuilder().setName('ban').setDescription('Üyeyi yasaklar').setDefaultMemberPermissions(P.BanMembers).addUserOption(U('Yasaklanacak üye')).addStringOption(reason),
new SlashCommandBuilder().setName('kick').setDescription('Üyeyi sunucudan atar').setDefaultMemberPermissions(P.KickMembers).addUserOption(U('Atılacak üye')).addStringOption(reason),
new SlashCommandBuilder().setName('timeout').setDescription('Üyeye zaman aşımı uygular').setDefaultMemberPermissions(P.ModerateMembers).addUserOption(U('Üye')).addIntegerOption(o=>o.setName('dakika').setDescription('Dakika').setMinValue(1).setMaxValue(40320).setRequired(true)).addStringOption(reason),
new SlashCommandBuilder().setName('untimeout').setDescription('Zaman aşımını kaldırır').setDefaultMemberPermissions(P.ModerateMembers).addUserOption(U('Üye')),
new SlashCommandBuilder().setName('temizle').setDescription('Toplu mesaj siler').setDefaultMemberPermissions(P.ManageMessages).addIntegerOption(o=>o.setName('miktar').setDescription('1-100').setMinValue(1).setMaxValue(100).setRequired(true)),
new SlashCommandBuilder().setName('uyar').setDescription('Sicile uyarı ekler').setDefaultMemberPermissions(P.ModerateMembers).addUserOption(U('Üye')).addStringOption(o=>reason(o).setRequired(true)),
new SlashCommandBuilder().setName('sicil').setDescription('Üye sicil kartı').setDefaultMemberPermissions(P.ModerateMembers).addUserOption(U('Üye')).addBooleanOption(o=>o.setName('temizle').setDescription('Uyarıları temizle')),
new SlashCommandBuilder().setName('guvenlik').setDescription('Güvenlik modülleri').setDefaultMemberPermissions(P.Administrator).addStringOption(o=>o.setName('modul').setDescription('Koruma').setRequired(true).addChoices({name:'Durum',value:'durum'},{name:'Anti nuke',value:'antiNuke'},{name:'Anti link',value:'antiLink'},{name:'Anti küfür',value:'antiSwear'},{name:'Anti spam',value:'antiSpam'})).addBooleanOption(o=>o.setName('aktif').setDescription('Aç veya kapat')),
new SlashCommandBuilder().setName('otorol').setDescription('Yeni üye rolü').setDefaultMemberPermissions(P.Administrator).addRoleOption(o=>o.setName('rol').setDescription('Rol')),
new SlashCommandBuilder().setName('modlog').setDescription('Görsel log kanalı').setDefaultMemberPermissions(P.Administrator).addChannelOption(o=>o.setName('kanal').setDescription('Kanal')),
new SlashCommandBuilder().setName('dogrulama-kur').setDescription('Görsel doğrulama paneli').setDefaultMemberPermissions(P.Administrator).addRoleOption(R('Doğrulama rolü')),
new SlashCommandBuilder().setName('ticket-kur').setDescription('Görsel destek paneli').setDefaultMemberPermissions(P.Administrator).addStringOption(o=>o.setName('baslik').setDescription('Başlık')).addRoleOption(o=>o.setName('yetkili').setDescription('Yetkili rolü')).addChannelOption(o=>o.setName('kategori').setDescription('Kategori')),
new SlashCommandBuilder().setName('rol-panel').setDescription('Görsel rol paneli').setDefaultMemberPermissions(P.Administrator).addRoleOption(R('İlk rol')).addRoleOption(o=>o.setName('rol2').setDescription('İkinci rol')).addRoleOption(o=>o.setName('rol3').setDescription('Üçüncü rol')).addRoleOption(o=>o.setName('rol4').setDescription('Dördüncü rol')),
new SlashCommandBuilder().setName('seviye-odul').setDescription('Seviye rol ödülleri').setDefaultMemberPermissions(P.Administrator).addStringOption(o=>o.setName('islem').setDescription('İşlem').setRequired(true).addChoices({name:'Ekle',value:'ekle'},{name:'Sil',value:'sil'},{name:'Liste',value:'liste'})).addIntegerOption(o=>o.setName('seviye').setDescription('Seviye').setMinValue(1)).addRoleOption(o=>o.setName('rol').setDescription('Rol')),
new SlashCommandBuilder().setName('cekilis').setDescription('Görsel çekiliş').setDefaultMemberPermissions(P.ManageGuild).addStringOption(o=>o.setName('odul').setDescription('Ödül').setRequired(true)).addIntegerOption(o=>o.setName('dakika').setDescription('Dakika').setMinValue(1).setMaxValue(10080).setRequired(true)).addIntegerOption(o=>o.setName('kazanan').setDescription('Kazanan').setMinValue(1).setMaxValue(10)),
new SlashCommandBuilder().setName('cal').setDescription('Ses kanalında müzik çalar').addStringOption(o=>o.setName('sarki').setDescription('Arama veya bağlantı').setRequired(true))];
module.exports={commandData};
